# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dnormC <- function(x) {
    .Call('scoringRules_dnormC', PACKAGE = 'scoringRules', x)
}

pnormC <- function(x) {
    .Call('scoringRules_pnormC', PACKAGE = 'scoringRules', x)
}

auxcrpsC <- function(m, s) {
    .Call('scoringRules_auxcrpsC', PACKAGE = 'scoringRules', m, s)
}

crpsmixnC <- function(w, m, s, y) {
    .Call('scoringRules_crpsmixnC', PACKAGE = 'scoringRules', w, m, s, y)
}

lsmixnC <- function(w, m, s, y) {
    .Call('scoringRules_lsmixnC', PACKAGE = 'scoringRules', w, m, s, y)
}

