# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

auxcrpsC <- function(m, s) {
    .Call(`_scoringRules_auxcrpsC`, m, s)
}

crpsmixnC <- function(w, m, s, y) {
    .Call(`_scoringRules_crpsmixnC`, w, m, s, y)
}

lsmixnC <- function(w, m, s, y) {
    .Call(`_scoringRules_lsmixnC`, w, m, s, y)
}

dssmixnC <- function(w, m, s, y) {
    .Call(`_scoringRules_dssmixnC`, w, m, s, y)
}

dmixnC <- function(m, s, y) {
    .Call(`_scoringRules_dmixnC`, m, s, y)
}

pmixnC <- function(m, s, y) {
    .Call(`_scoringRules_pmixnC`, m, s, y)
}

mvndrawC <- function(mu, sig) {
    .Call(`_scoringRules_mvndrawC`, mu, sig)
}

carterkohn <- function(y, Z, Ht, Qt, m, p, t, B0, V0) {
    .Call(`_scoringRules_carterkohn`, y, Z, Ht, Qt, m, p, t, B0, V0)
}

drawsigmaC <- function(yts, qs, ms, u2s, Sigtdraw, Zs, Wdraw, sigma_prmean, sigma_prvar) {
    .Call(`_scoringRules_drawsigmaC`, yts, qs, ms, u2s, Sigtdraw, Zs, Wdraw, sigma_prmean, sigma_prvar)
}

drawbetaC <- function(y, Z, s2, betapriorm, betaprioriv) {
    .Call(`_scoringRules_drawbetaC`, y, Z, s2, betapriorm, betaprioriv)
}

makeregs_fcC <- function(ydat, p) {
    .Call(`_scoringRules_makeregs_fcC`, ydat, p)
}

getfcsts <- function(beta, Sigt0, Wdraw, ydat, nf, p) {
    .Call(`_scoringRules_getfcsts`, beta, Sigt0, Wdraw, ydat, nf, p)
}

meye <- function(n) {
    .Call(`_scoringRules_meye`, n)
}

matmult <- function(x, nt) {
    .Call(`_scoringRules_matmult`, x, nt)
}

bvarFcstC <- function(b, sig, y, nf) {
    .Call(`_scoringRules_bvarFcstC`, b, sig, y, nf)
}

drawMultinomC <- function(probs) {
    .Call(`_scoringRules_drawMultinomC`, probs)
}

filterMarkovMixtureC <- function(p, P, lnpdat) {
    .Call(`_scoringRules_filterMarkovMixtureC`, p, P, lnpdat)
}

euclnormC <- function(x) {
    .Call(`_scoringRules_euclnormC`, x)
}

vsC <- function(y, dat, p) {
    .Call(`_scoringRules_vsC`, y, dat, p)
}

vsC_w_vs <- function(y, dat, w_vs, p) {
    .Call(`_scoringRules_vsC_w_vs`, y, dat, w_vs, p)
}

vskernelC <- function(x1, x2, w_vs, p) {
    .Call(`_scoringRules_vskernelC`, x1, x2, w_vs, p)
}

vsC_w <- function(y, dat, w_vs, w, p) {
    .Call(`_scoringRules_vsC_w`, y, dat, w_vs, w, p)
}

energyscoreC <- function(y, dat, w) {
    .Call(`_scoringRules_energyscoreC`, y, dat, w)
}

esC_xx <- function(dat, w) {
    .Call(`_scoringRules_esC_xx`, dat, w)
}

esC_xy <- function(y, dat, w) {
    .Call(`_scoringRules_esC_xy`, y, dat, w)
}

mmdscoreC <- function(y, dat, w) {
    .Call(`_scoringRules_mmdscoreC`, y, dat, w)
}

mmdsC_xx <- function(dat, w) {
    .Call(`_scoringRules_mmdsC_xx`, dat, w)
}

mmdsC_xy <- function(y, dat, w) {
    .Call(`_scoringRules_mmdsC_xy`, y, dat, w)
}

